export const codeElements = [
  { type: "language", content: "HTML", color: "text-orange-500", size: "text-lg" },
  { type: "language", content: "CSS", color: "text-blue-500", size: "text-lg" },
  { type: "language", content: "JavaScript", color: "text-yellow-400", size: "text-lg" },
  { type: "language", content: "TypeScript", color: "text-blue-400", size: "text-lg" },
  { type: "language", content: "React", color: "text-cyan-400", size: "text-lg" },
  { type: "language", content: "Next.js", color: "text-gray-300", size: "text-lg" },
  { type: "language", content: "Node.js", color: "text-green-500", size: "text-lg" },
  { type: "language", content: "Express.js", color: "text-gray-500", size: "text-lg" },
  { type: "language", content: "MongoDB", color: "text-green-400", size: "text-lg" },
  { type: "language", content: "MySQL", color: "text-blue-300", size: "text-lg" },
  { type: "language", content: "PostgreSQL", color: "text-indigo-400", size: "text-lg" },
  { type: "language", content: "Python", color: "text-yellow-300", size: "text-lg" },
  { type: "language", content: "Django", color: "text-green-600", size: "text-lg" },
  { type: "language", content: "Java", color: "text-red-400", size: "text-lg" },
  { type: "language", content: "Spring Boot", color: "text-green-400", size: "text-lg" },
  { type: "language", content: "C++", color: "text-blue-400", size: "text-lg" },
  { type: "language", content: "C#", color: "text-purple-500", size: "text-lg" },
  { type: "language", content: "PHP", color: "text-indigo-300", size: "text-lg" },
  { type: "language", content: "Laravel", color: "text-red-500", size: "text-lg" },
  { type: "language", content: "Firebase", color: "text-amber-400", size: "text-lg" },
  { type: "language", content: "Tailwind CSS", color: "text-sky-400", size: "text-lg" },
  { type: "language", content: "Bootstrap", color: "text-purple-300", size: "text-lg" },
  { type: "language", content: "GraphQL", color: "text-pink-400", size: "text-lg" },
  { type: "language", content: "REST API", color: "text-teal-300", size: "text-lg" },
  { type: "language", content: "Git", color: "text-orange-400", size: "text-lg" },
  { type: "language", content: "GitHub", color: "text-white", size: "text-lg" },
];
