export const trainersData = [
  {
    id: 1,
    name: "ALEX RODRIGUEZ",
    title: "HEAD TRAINER",
    speciality: "STRENGTH & CONDITIONING",
    experience: "10+ YEARS",
    image: "/assets/trainers/trainer-1.jpg",
    bio: "Former Olympic athlete specializing in functional strength training and athletic performance. Dedicated to helping clients achieve their peak physical condition.",
    skills: [
      "Olympic Lifting",
      "CrossFit",
      "Athletic Performance",
      "Injury Prevention",
    ],
    certifications: ["NASM-CPT", "CSCS", "Olympic Weightlifting"],
    price: "$80/session",
    duration: "60 mins",
    availability: "Mon-Fri",
  },
  {
    id: 2,
    name: "SARAH CHEN",
    title: "YOGA INSTRUCTOR",
    speciality: "MINDFULNESS & FLEXIBILITY",
    experience: "6+ YEARS",
    image: "/assets/trainers/trainer-2.jpg",
    bio: "Certified yoga instructor with expertise in Vinyasa, Hatha, and therapeutic yoga practices. Passionate about mind-body wellness.",
    skills: ["Vinyasa Flow", "Meditation", "Breathwork", "Therapeutic Yoga"],
    certifications: ["RYT-500", "Yin Yoga", "Meditation Teacher"],
    price: "$65/session",
    duration: "75 mins",
    availability: "Daily",
  },
  {
    id: 3,
    name: "MARCUS JOHNSON",
    title: "BOXING COACH",
    speciality: "COMBAT SPORTS",
    experience: "7+ YEARS",
    image: "/assets/trainers/trainee-4.jpg",
    bio: "Professional boxing coach with championship experience in amateur and professional circuits. Expert in technique and mental conditioning.",
    skills: [
      "Boxing Technique",
      "Pad Work",
      "Conditioning",
      "Mental Toughness",
    ],
    certifications: ["USA Boxing", "Golden Gloves", "Strength Coach"],
    price: "$75/session",
    duration: "45 mins",
    availability: "Tue-Sat",
  },
  // {
  //     id: 4,
  //     name: "EMMA WILLIAMS",
  //     title: "NUTRITION SPECIALIST",
  //     speciality: "SPORTS NUTRITION",
  //     experience: "7+ YEARS",
  //     image: "/assets/trainers/trainer-1.jpg",
  //     bio: "Registered dietitian specializing in sports nutrition and body composition optimization. Helping athletes fuel their performance.",
  //     skills: ["Meal Planning", "Supplement Guidance", "Body Composition", "Performance Nutrition"],
  //     certifications: ["RD", "CSSD", "Precision Nutrition"],
  //     price: "$90/consultation",
  //     duration: "90 mins",
  //     availability: "Mon-Thu",
  // },
  // {
  //     id: 5,
  //     name: "DAVID THOMPSON",
  //     title: "CARDIO SPECIALIST",
  //     speciality: "ENDURANCE TRAINING",
  //     experience: "5+ YEARS",
  //     image: "/assets/trainers/trainer-1.jpg",
  //     bio: "Marathon runner and triathlete focused on cardiovascular health and endurance performance. Building stamina and endurance.",
  //     skills: ["Running Technique", "HIIT Training", "Endurance Coaching", "Recovery Methods"],
  //     certifications: ["ACSM-CPT", "Running Coach", "Triathlon Coach"],
  //     price: "$70/session",
  //     duration: "50 mins",
  //     availability: "Daily",
  // },
  // {
  //     id: 6,
  //     name: "LISA MARTINEZ",
  //     title: "PILATES INSTRUCTOR",
  //     speciality: "CORE & STABILITY",
  //     experience: "3+ YEARS",
  //     image: "/assets/trainers/trainer-1.jpg",
  //     bio: "Master Pilates instructor specializing in rehabilitation and core strengthening programs. Focus on proper alignment and movement.",
  //     skills: ["Classical Pilates", "Reformer", "Mat Work", "Injury Rehabilitation"],
  //     certifications: ["PMA-CPT", "Reformer Certified", "Rehabilitation Specialist"],
  //     price: "$85/session",
  //     duration: "55 mins",
  //     availability: "Mon-Fri",
  // },
];
